swagger: '2.0'
info:
  description: 'Stream api for Hercules. Uses for read the stream content.'
  version: 1.2.0
  title: Hercules stream API
host: 'vm-hercules05:6307'
schemes:
  - http
paths:
  /ping:
    get:
      summary: Ping
      description: Check server status
      operationId: ping
      responses:
        '200':
          $ref: '#/responses/success'
  /about:
    get:
      summary: About
      description: Check server description
      operationId: about
      responses:
        '200':
          description: Info about service
          schema:
            $ref: '#/definitions/about'
  /stream/seekToEnd:
    get:
      tags:
        - stream
      summary: Stream
      description: Seek the end of the stream
      operationId: seekEndOfStream
      produces:
        - application/octet-stream
      parameters:
        - $ref: '#/parameters/apiKey'
        - $ref: '#/parameters/contentType'
        - name: stream
          in: query
          description: Stream name
          required: true
          type: string
          pattern: '[a-z0-9_]{1,48}'
        - name: shardIndex
          in: query
          description: The logical shard index. Starts with `0` up to `shardCount - 1`
          required: true
          type: integer
        - name: shardCount
          in: query
          description: The total logical shards
          required: true
          type: integer
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/readRulesIsAbsent'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/notFoundSourceStream'
        '500':
          $ref: '#/responses/internalServiceError'
  /stream/read:
    post:
      tags:
        - stream
      summary: Strean
      description: Read the stream content
      operationId: readStream
      produces:
        - application/octet-stream
      parameters:
        - $ref: '#/parameters/apiKey'
        - $ref: '#/parameters/contentType'
        - name: stream
          in: query
          description: Stream name
          required: true
          type: string
          pattern: '[a-z0-9_]{1,48}'
        - name: shardIndex
          in: query
          description: The logical shard index. Starts with `0` up to `shardCount - 1`
          required: true
          type: integer
        - name: shardCount
          in: query
          description: The total logical shards
          required: true
          type: integer
        - name: take
          in: query
          description: Maximum events to read
          required: true
          type: integer
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/readRulesIsAbsent'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/notFoundSourceStream'
        '411':
          $ref: '#/responses/lengthRequired'
        '500':
          $ref: '#/responses/internalServiceError'
definitions:
  about:
    type: object
    properties:
      applicationName:
        type: string
      applicationId:
        type: string
      version:
        type: string
      commitId:
        type: string
      environment:
        type: string
      zone:
        type: string
      hostName:
        type: string
      instanceId:
        type: string
parameters:
  apiKey:
    name: Authorization
    in: header
    type: string
    pattern: '^Hercules apiKey .+'
    required: true
    description: API key for authorization
  contentType:
    name: contentType
    in: header
    type: string
    required: true
    description: application/octet-stream
responses:
  success:
    description: OK
  badRequest:
    description: Bad request
  readRulesIsAbsent:
    description: Read rules for this apiKey is absent
  forbidden:
    description: Forbidden for this API-key
  notFoundSourceStream:
    description: Not found source stream
  lengthRequired:
    description: Can't get Content-Length value
  internalServiceError:
    description: Internal service error
