FROM openjdk:8-jre-alpine

ARG SERVICENAME="unknown"
ARG VERSION="unknown"

WORKDIR "/usr/lib/${SERVICENAME}"

ENV VERSION=${VERSION}
ENV JAVAOPTS=""
ENV SETTINGS="/etc/${SERVICENAME}"

COPY ${SERVICENAME}/target/${SERVICENAME}-${VERSION}.jar ${WORKDIR}/${SERVICENAME}-${VERSION}.jar

ENTRYPOINT java ${JAVAOPTS} -jar ${SERVICENAME}-${VERSION}.jar application.properties=${SETTINGS} 

