package ru.kontur.vostok.hercules.sentry.client.impl.client.v7.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Levels of log available in Sentry.
 *
 * @author Tatyana Tokmyanina
 */
public enum SentryLevel {

    /**
     * Fatal is the highest form of log available, use it for unrecoverable issues.
     */
    @JsonProperty("fatal")
    FATAL,
    /**
     * Error denotes an unexpected behaviour that prevented the code to work properly.
     */
    @JsonProperty("error")
    ERROR,
    /**
     * Warning should be used to define logs generated by expected and handled bad behaviour.
     */
    @JsonProperty("warning")
    WARNING,
    /**
     * Info is used to give general details on the running application, usually only messages.
     */
    @JsonProperty("info")
    INFO,
    /**
     * Debug information to track every detail of the application execution process.
     */
    @JsonProperty("debug")
    DEBUG
}
